import keyMirror from 'key-mirror'

export default keyMirror({
  SET_PLATFORM: null,
  SET_VERSION: null,

  SESSION_TOKEN_REQUEST: null,
  SESSION_TOKEN_SUCCESS: null,
  SESSION_TOKEN_FAILURE: null,

  DELETE_TOKEN_REQUEST: null,
  DELETE_TOKEN_SUCCESS: null,

  ON_LOGIN_STATE_CHANGE: null,
  LOGOUT: null,

  ON_AUTH_FORM_FIELD_CHANGE: null,
  SIGNUP_REQUEST: null,
  SIGNUP_SUCCESS: null,
  SIGNUP_FAILURE: null,

  LOGIN_REQUEST: null,
  LOGIN_SUCCESS: null,
  LOGIN_FAILURE: null,

  LOGOUT_REQUEST: null,
  LOGOUT_SUCCESS: null,
  LOGOUT_FAILURE: null,

  LOGGED_IN: null,
  LOGGED_OUT: null,

  SET_SESSION_TOKEN: null,

  RESET_PASSWORD_REQUEST: null,
  RESET_PASSWORD_SUCCESS: null,
  RESET_PASSWORD_FAILURE: null,

  GET_PROFILE_REQUEST: null,
  GET_PROFILE_SUCCESS: null,
  GET_PROFILE_FAILURE: null,

  ON_PROFILE_FORM_FIELD_CHANGE: null,

  PROFILE_UPDATE_REQUEST: null,
  PROFILE_UPDATE_SUCCESS: null,
  PROFILE_UPDATE_FAILURE: null,

  SET_STATE: null,
  GET_STATE: null,
  SET_STORE: null,

  FORGOT_PASSWORD: null,
  LOGIN: null,
  REGISTER: null,

  GET_POPULAR_REQUEST: null,
  GET_POPULAR_SUCCESS: null,
  GET_POPULAR_FAILURE: null,

  GET_CATEGORIES_REQUEST: null,
  GET_CATEGORIES_SUCCESS: null,
  GET_CATEGORIES_FAILURE: null,

  GET_CATEGORY_REQUEST: null,
  GET_CATEGORY_SUCCESS: null,
  GET_CATEGORY_FAILURE: null,

  GET_EPISODES_REQUEST: null,
  GET_EPISODES_SUCCESS: null,
  GET_EPISODES_FAILURE: null,

  GET_EPISODE_REQUEST: null,
  GET_EPISODE_SUCCESS: null,
  GET_EPISODE_FAILURE: null,

  GET_PODCAST_SUCCESS: null,
  GET_PODCAST_FAILURE: null,

  GET_SEARCH_REQUEST: null,
  GET_SEARCH_SUCCESS: null,
  GET_SEARCH_FAILURE: null,

  SEARCH_SHOWS_REQUEST: null,
  SEARCH_SHOWS_SUCCESS: null,
  SEARCH_SHOWS_FAILURE: null,


  HAS_TAG_REQUEST: null,
  HAS_TAG_SUCCESS: null,
  HAS_TAG_FAILURE: null,

  GET_TAGGED_SHOWS_REQUEST: null,
  GET_TAGGED_SHOWS_SUCCESS: null,
  GET_TAGGED_SHOWS_FAILURE: null,

  GET_TAGS_REQUEST: null,
  GET_TAGS_SUCCESS: null,
  GET_TAGS_FAILURE: null,


  PLAYER_PLAY_REQUEST: null,
  PLAYER_RESUME_REQUEST: null,
  PLAYER_PAUSE_REQUEST: null,
  PLAYER_STOP_REQUEST: null,
  PLAYER_START_REQUEST: null,
  PLAYER_SEEKTO_REQUEST: null,
  PLAYER_GOBACK_REQUEST: null,
  PLAYER_GOFORWARD_REQUEST: null,

  PLAYER_PLAY_SUCCESS: null,
  PLAYER_RESUME_SUCCESS: null,
  PLAYER_PAUSE_SUCCESS: null,
  PLAYER_STOP_SUCCESS: null,
  PLAYER_START_SUCCESS: null,
  PLAYER_SEEKTO_SUCCESS: null,
  PLAYER_GOBACK_SUCCESS: null,
  PLAYER_GOFORWARD_SUCCESS: null,

  PLAYER_PLAY_FAILURE: null,
  PLAYER_RESUME_FAILURE: null,
  PLAYER_PAUSE_FAILURE: null,
  PLAYER_STOP_FAILURE: null,
  PLAYER_START_FAILURE: null,
  PLAYER_SEEKTO_FAILURE: null,
  PLAYER_GOBACK_FAILURE: null,
  PLAYER_GOFORWARD_FAILURE: null,

  PLAYER_MAXIMIZE_SUCCESS: null,
  PLAYER_MINIMIZE_SUCCESS: null,

  SET_PODCAST_HISTORY_REQUEST: null,
  SET_PODCAST_HISTORY_SUCCESS: null,
  SET_PODCAST_HISTORY_FAILURE: null,

  REMOVE_PODCAST_HISTORY_REQUEST: null,
  REMOVE_PODCAST_HISTORY_SUCCESS: null,
  REMOVE_PODCAST_HISTORY_FAILURE: null,

  SET_SUBSCRIPTION_REQUEST: null,
  SET_SUBSCRIPTION_SUCCESS: null,
  SET_SUBSCRIPTION_FAILURE: null,

  REMOVE_SUBSCRIPTION_REQUEST: null,
  REMOVE_SUBSCRIPTION_SUCCESS: null,

  GET_ALL_PODCAST_HISTORY_SUCCESS: null,

  GET_ALL_SUBSCRIPTION_EPISODES_SUCCESS: null,

  GET_NEXT_PODCAST_HISTORY_REQUEST: null,
  GET_NEXT_PODCAST_HISTORY_SUCCESS: null,
  GET_NEXT_PODCAST_HISTORY_FAILURE: null,

  GET_ALL_SUBSCRIPTION_SUCCESS: null,


})
